name: craftisa-deploy
on:
    push:
        branches: ["main"]

jobs:
    see-changes:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - name: Get changed directories
            id: changes
            run: |
              CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F '/' '{print $1}' | sort -u | uniq | grep -E 'catalogue|front|recco|voting' || true)
              if [[ -n "$CHANGED_DIRS" ]]; then
                echo "changed_dirs=$(echo $CHANGED_DIRS | jq -R -s -c 'split(" ")')" >> $GITHUB_ENV
              else
                echo "changed_dirs=[]" >> $GITHUB_ENV
              fi
    
        outputs:
          changed_dirs: ${{ env.changed_dirs }}

    build:
        needs: see-changes
        if: needs.see-changes.outputs.changed_dirs != '[]'
        strategy:
            matrix:
              dir: ${{ fromJson(needs.build-and-push.outputs.changed_dirs) }}

        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Docker Hub Auth
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
    
        - name: Build das imagens docker
          if: env.CHANGED_DIRS != ''
          uses: docker/build-push-action@v5
          with:
            context: ./${{ matrix.dir }}
            file: ./${{ matrix.dir }}/Dockerfile
            push: true
            tags: |
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-${{ matrix.dir }}:v${{ github.run_number }} 
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}-${{ matrix.dir }}:latest
